#!/usr/bin/php
<?php


if (php_sapi_name() !== 'cli') {
    exit;
}
define('PROJECT_ROOT', dirname(__FILE__));

use engines\rahisicli\App;
use Symfony\Component\Dotenv\Dotenv;
use support\Database\DB;
use support\Database\schema;
use support\Routing\Route;
use engines\rahisicli\contoller\makeController;


require __DIR__ . '/vendor/autoload.php';
include "./App/Helper.php";
$dotenv = new Dotenv();
$dotenv->load(__DIR__.'/.env');

$app = new App();

try {
    $app->runCommand($argv);
} catch (\Throwable $th) {
    throw $th;
}